export class NitroCommunicationEventEnum
{
    public static CONNECTION_ESTABLISHED        = 'CONNECTION_ESTABLISHED';
    public static CONNECTION_HANDSHAKING        = 'CONNECTION_HANDSHAKING';
    public static CONNECTION_HANDSHAKED         = 'CONNECTION_HANDSHAKED';
    public static CONNECTION_HANDSHAKE_FAILED   = 'CONNECTION_HANDSHAKE_FAILED';
    public static CONNECTION_AUTHENTICATED      = 'CONNECTION_AUTHENTICATED';
}